
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 20.6.0 - x86_64
...
